#include <fcntl.h>
#include <limits.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>

#ifdef __cplusplus
#include <list>

// Qt headers
#include <q3accel.h>
#include <q3combobox.h>
#include <q3dns.h>
#include <q3dragobject.h>
#include <q3filedialog.h>
#include <Q3GridLayout>
#include <Q3GroupBox>
#include <q3hgroupbox.h>
#include <Q3ListBox>
#include <q3listview.h>
#include <q3mainwindow.h>
#include <Q3MimeSourceFactory>
#include <q3multilineedit.h>
#include <Q3PopupMenu>
#include <q3stylesheet.h>
#include <q3textbrowser.h>
#include <q3textview.h>
#include <Q3ValueList>
#include <q3vbox.h>
#include <q3vgroupbox.h>
#include <QAction>
#include <QApplication>
#include <qboxlayout.h>
#include <QButtonGroup>
#include <QByteArray>
#include <qcdestyle.h>
#include <QCheckBox>
#include <qcolordialog.h>
#include <QComboBox>
#include <qcoreevent.h>
#include <QCustomEvent>
#include <qdatetime.h>
#include <QDesktopWidget>
#include <QDialog>
#include <qdir.h>
#include <QDragEnterEvent>
#include <QDropEvent>
#include <QEvent>
#include <qfiledialog.h>
#include <qfile.h>
#include <qfileinfo.h>
#include <QFocusEvent>
#include <qfont.h>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QHideEvent>
#include <qimage.h>
#include <QImageReader>
#include <qinputdialog.h>
#include <QKeyEvent>
#include <QLabel>
#include <qlayout.h>
#include <QLineEdit>
#include <qlistview.h>
#include <qmenubar.h>
#include <qmessagebox.h>
#include <qmotifstyle.h>
#include <QMouseEvent>
#include <qmutex.h>
#include <qobject.h>
#include <qpainter.h>
#include <qpalette.h>
#include <QPixmap>
#include <qplastiquestyle.h>
#include <QPushButton>
#include <qregexp.h>
#include <QResizeEvent>
#include <QShowEvent>
#include <qsound.h>
#include <QSpacerItem>
#include <QSpinBox>
#include <qsplitter.h>
#include <qstatusbar.h>
#include <QString>
#include <qstringlist.h>
#include <QTabWidget>
#include <qtextbrowser.h>
#include <qtextcodec.h>
#include <qthread.h>
#include <QTimerEvent>
#include <qtimer.h>
#include <qtoolbar.h>
#include <qtooltip.h>
#include <QTranslator>
#include <QVariant>
#include <QVBoxLayout>
#include <qwaitcondition.h>
#include <QWidget>
#include <qwindowsstyle.h>
#include <qwindowsvistastyle.h>
#include <qwindowsxpstyle.h>

#endif
