all : cyr2utf ekr2utf lat2utf urldecode utf2cyr utf2ekr utf2lat
cyr2utf :
	$(MAKE) -C $@
ekr2utf :
	$(MAKE) -C $@
lat2utf :
	$(MAKE) -C $@
urldecode :
	$(MAKE) -C $@
utf2cyr :
	$(MAKE) -C $@
utf2ekr :
	$(MAKE) -C $@
utf2lat :
	$(MAKE) -C $@

.PHONY : cyr2utf ekr2utf lat2utf urldecode utf2cyr utf2ekr utf2lat
